import type { Motorcycle } from './types';

export const BRANDS = ['CFLITE', 'CFMOTO', 'Fantic', 'MV Agusta', 'VOGE', 'ZEEHO'];

export const COLORS = [
  { label: 'Black', value: 'Black' },
  { label: 'Black/Red', value: 'Black/Red' },
  { label: 'Black/Red/Blue', value: 'Black/Red/Blue' },
  { label: 'Black/Yellow', value: 'Black/Yellow' },
  { label: 'Blue', value: 'Blue' },
  { label: 'Green', value: 'Green' },
  { label: 'White', value: 'White' },
  { label: 'Red', value: 'Red' },
];

export const YEARS = [2022, 2023, 2024, 2025, 2026];
export const POWER_MIN = 5;
export const POWER_MAX = 130;

export const COLOR_SWATCHES: Record<string, string> = {
  Black: '#111827',
  'Black/Red': 'linear-gradient(135deg, #111827 50%, #dc2626 50%)',
  'Black/Red/Blue': 'linear-gradient(135deg, #111827 33%, #dc2626 33%, #dc2626 66%, #2563eb 66%)',
  'Black/Yellow': 'linear-gradient(135deg, #111827 50%, #eab308 50%)',
  Blue: '#2563eb',
  Green: '#16a34a',
  White: '#f3f4f6',
  Red: '#dc2626',
};

export const BRAND_GRADIENTS: Record<string, string> = {
  CFLITE: 'from-indigo-900 to-slate-950',
  CFMOTO: 'from-slate-700 to-slate-950',
  Fantic: 'from-emerald-900 to-slate-950',
  'MV Agusta': 'from-rose-900 to-slate-950',
  VOGE: 'from-amber-900 to-slate-950',
  ZEEHO: 'from-cyan-900 to-slate-950',
};

export const motorcycles: Motorcycle[] = [
  {
    id: 1,
    name: "ZEEHO C!TY SPORT '24",
    brand: 'ZEEHO',
    year: 2024,
    color: 'Black/Red',
    powerKw: 12,
    engine: 'Electric 12kW PMSM Motor',
    price: 4999,
    inStock: true,
    matriculate: 'BG 1234 AB',
    licenseCategories: ['A1', 'B'],
  },
  {
    id: 2,
    name: "CFMOTO 450NK '25",
    brand: 'CFMOTO',
    year: 2025,
    color: 'Black',
    powerKw: 38,
    engine: '449cc Parallel Twin, DOHC',
    price: 6290,
    inStock: true,
    matriculate: 'BG 5678 CD',
    licenseCategories: ['A2'],
  },
  {
    id: 3,
    name: "MV Agusta Brutale 800 '24",
    brand: 'MV Agusta',
    year: 2024,
    color: 'Black/Red',
    powerKw: 87,
    engine: '798cc Triple, DOHC 12V',
    price: 14990,
    inStock: false,
    matriculate: 'BG 9012 EF',
    licenseCategories: ['A'],
  },
  {
    id: 4,
    name: "VOGE 525DSX '25",
    brand: 'VOGE',
    year: 2025,
    color: 'Black/Yellow',
    powerKw: 47,
    engine: '500cc Single-Cylinder',
    price: 7490,
    inStock: true,
    matriculate: 'BG 3456 GH',
    licenseCategories: ['A2'],
  },
  {
    id: 5,
    name: "Fantic Caballero 700 '24",
    brand: 'Fantic',
    year: 2024,
    color: 'Green',
    powerKw: 55,
    engine: '693cc Parallel Twin, Euro 5',
    price: 9890,
    inStock: true,
    matriculate: 'BG 7890 IJ',
    licenseCategories: ['A'],
  },
  {
    id: 6,
    name: "CFLITE K19 '26",
    brand: 'CFLITE',
    year: 2026,
    color: 'Blue',
    powerKw: 8,
    engine: 'Electric 8kW Hub Motor',
    price: 3890,
    inStock: true,
    matriculate: 'BG 2345 KL',
    licenseCategories: ['A1', 'B'],
  },
  {
    id: 7,
    name: "CFMOTO 700CL-X Sport '25",
    brand: 'CFMOTO',
    year: 2025,
    color: 'Black/Red/Blue',
    powerKw: 55,
    engine: '693cc Parallel Twin, Euro 5+',
    price: 8990,
    inStock: false,
    matriculate: 'BG 6789 MN',
    licenseCategories: ['A'],
  },
  {
    id: 8,
    name: "MV Agusta Dragster B '23",
    brand: 'MV Agusta',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple, DOHC 12V RR',
    price: 18990,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
  },
];
