import type { Motorcycle } from './types';

export const BRANDS = ['CFLITE', 'CFMOTO', 'Fantic', 'MV Agusta', 'VOGE', 'ZEEHO'];

export const COLORS = [
  { label: 'Black', value: 'Black' },
  { label: 'Black/Red', value: 'Black/Red' },
  { label: 'Black/Red/Blue', value: 'Black/Red/Blue' },
  { label: 'Black/Yellow', value: 'Black/Yellow' },
  { label: 'Blue', value: 'Blue' },
  { label: 'Green', value: 'Green' },
  { label: 'White', value: 'White' },
  { label: 'Red', value: 'Red' },
];

export const YEARS = [2022, 2023, 2024, 2025, 2026];
export const POWER_MIN = 5;
export const POWER_MAX = 130;

export const COLOR_SWATCHES: Record<string, string> = {
  Black: '#111827',
  'Black/Red': 'linear-gradient(135deg, #111827 50%, #dc2626 50%)',
  'Black/Red/Blue': 'linear-gradient(135deg, #111827 33%, #dc2626 33%, #dc2626 66%, #2563eb 66%)',
  'Black/Yellow': 'linear-gradient(135deg, #111827 50%, #eab308 50%)',
  Blue: '#2563eb',
  Green: '#16a34a',
  White: '#f3f4f6',
  Red: '#dc2626',
};

export const BRAND_TOKENS: Record<string, string> = {
  CFLITE: '#00A99D',
  CFMOTO: '#2A2A2A',
  Fantic: '#1F3B2A',
  'MV Agusta': '#7B1F2E',
  VOGE: '#8B5A2B',
  ZEEHO: '#00C2A8',
};

export const motorcycles: Motorcycle[] = [
  {
    id: 1,
    name: "ZEEHO C!TY SPORT '25",
    model: 'C!TY SPORT',
    brand: 'ZEEHO',
    brandGradient: 'linear-gradient(to bottom, #001a1a, #003333, #004040)',
    year: 2025,
    color: 'Black/Red',
    powerKw: 12,
    engine: 'Electric 12kW PMSM',
    price: 4999,
    inStock: true,
    matriculate: 'BG 1234 AB',
    licenseCategories: ['A1', 'B'],
    silhouetteCategory: 'electric',
  },
  {
    id: 2,
    name: "CFMOTO 450NK '25",
    model: '450NK',
    brand: 'CFMOTO',
    brandGradient: 'linear-gradient(to bottom, #0a0a14, #111128, #1a1a3a)',
    year: 2025,
    color: 'Black',
    powerKw: 38,
    engine: '449cc Parallel Twin',
    price: 6290,
    inStock: true,
    matriculate: 'BG 5678 CD',
    licenseCategories: ['A2'],
    silhouetteCategory: 'naked',
  },
  {
    id: 3,
    name: "MV Agusta BRUTALE 800 '24",
    model: 'BRUTALE 800',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2024,
    color: 'Black/Red',
    powerKw: 87,
    engine: '798cc Triple DOHC',
    price: 14990,
    inStock: false,
    matriculate: 'BG 9012 EF',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 4,
    name: "VOGE 525DSX '25",
    model: '525DSX',
    brand: 'VOGE',
    brandGradient: 'linear-gradient(to bottom, #1a0a00, #2d1500, #402000)',
    year: 2025,
    color: 'Black/Yellow',
    powerKw: 47,
    engine: '500cc Single-Cylinder',
    price: 7490,
    inStock: true,
    matriculate: 'BG 3456 GH',
    licenseCategories: ['A2'],
    silhouetteCategory: 'adventure',
  },
  {
    id: 5,
    name: "Fantic CABALLERO 700 '24",
    model: 'CABALLERO 700',
    brand: 'Fantic',
    brandGradient: 'linear-gradient(to bottom, #001200, #002200, #003300)',
    year: 2024,
    color: 'Green',
    powerKw: 55,
    engine: '693cc Parallel Twin',
    price: 9890,
    inStock: true,
    matriculate: 'BG 7890 IJ',
    licenseCategories: ['A'],
    silhouetteCategory: 'scrambler',
  },
  {
    id: 6,
    name: "CFLITE K19 '26",
    model: 'K19',
    brand: 'CFLITE',
    brandGradient: 'linear-gradient(to bottom, #000820, #001040, #001860)',
    year: 2026,
    color: 'Blue',
    powerKw: 8,
    engine: 'Electric 8kW Hub Motor',
    price: 3890,
    inStock: true,
    matriculate: 'BG 2345 KL',
    licenseCategories: ['A1', 'B'],
    silhouetteCategory: 'electric',
  },
  {
    id: 7,
    name: "CFMOTO 700CL-X SPORT '25",
    model: '700CL-X SPORT',
    brand: 'CFMOTO',
    brandGradient: 'linear-gradient(to bottom, #0a0a14, #111128, #1a1a3a)',
    year: 2025,
    color: 'Black/Red/Blue',
    powerKw: 55,
    engine: '693cc Parallel Twin',
    price: 11490,
    inStock: false,
    matriculate: 'BG 6789 MN',
    licenseCategories: ['A'],
    silhouetteCategory: 'sport',
  },
  {
    id: 8,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 9,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 10,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 11,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 12,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 13,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 14,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 15,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
  {
    id: 16,
    name: "MV Agusta DRAGSTER B '23",
    model: 'DRAGSTER B',
    brand: 'MV Agusta',
    brandGradient: 'linear-gradient(to bottom, #1a0008, #2d0010, #400018)',
    year: 2023,
    color: 'Black',
    powerKw: 95,
    engine: '798cc Triple DOHC RR',
    price: 12490,
    inStock: true,
    matriculate: 'BG 0123 OP',
    licenseCategories: ['A'],
    silhouetteCategory: 'naked',
  },
];
